name: fl_team
description: An example Flutter project using the hive and provider packages.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  fluttertoast: ^3.1.3
  google_fonts: ^1.0.0
  hive: ^1.4.1+1
  hive_flutter:
    git:
      url: git://github.com/chunghha/hive.git
      path: hive_flutter
  logger: ^0.8.3
  path_provider: ^1.6.7
  provider: ^4.0.4
  supercharged: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  hive_generator:
    git:
      url: git://github.com/chunghha/hive.git
      path: hive_generator

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
